export const routines = [
  {
    routine: 'Breakfast',
    id: 1,
    image:
      'https://images.unsplash.com/photo-1542691457-cbe4df041eb2?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1374&q=80',
  },
  {
    routine: 'Lunch',
    id: 2,
    image:
      'https://images.unsplash.com/photo-1601356616077-695728ae17cb?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1374&q=80',
  },
  {
    routine: 'Dinner',
    id: 3,
    image:
      'https://images.unsplash.com/photo-1586511925558-a4c6376fe65f?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1374&q=80',
  },
  {
    routine: 'Snacks',
    id: 4,
    image:
      'https://images.unsplash.com/photo-1528751014936-863e6e7a319c?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1372&q=80',
  },
];

export const categories = [
  {
    routine: 'Sweets',
    id: 1,
    image:
      'https://images.unsplash.com/photo-1591123220262-87ed377f7c08?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1473&q=80',
  },
  {
    routine: 'Dessert',
    id: 2,
    image:
      'https://images.unsplash.com/photo-1606313564200-e75d5e30476c?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1374&q=80',
  },
  {
    routine: 'Ice creams',
    id: 3,
    image:
      'https://images.unsplash.com/photo-1580915411954-282cb1b0d780?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1374&q=80',
  },
  {
    routine: 'Juices',
    id: 4,
    image:
      'https://images.unsplash.com/photo-1600271886742-f049cd451bba?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1374&q=80',
  },
  {
    routine: 'Cakes',
    id: 5,
    image:
      'https://images.unsplash.com/photo-1563729784474-d77dbb933a9e?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1374&q=80',
  },
  {
    routine: 'Soups',
    id: 6,
    image:
      'https://images.unsplash.com/photo-1603105037880-880cd4edfb0d?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1374&q=80',
  },
];

export const categoriesRecipes = [
  {
    name: 'Chocolate Chip Cookies',
    ingredients: [
      '2 1/4 cups all-purpose flour',
      '1/2 teaspoon baking soda',
      '1 cup unsalted butter, room temperature',
      '1/2 cup granulated sugar',
      '1 cup brown sugar',
      '1 teaspoon salt',
      '2 teaspoons pure vanilla extract',
      '2 large eggs',
      '2 cups semisweet and/or milk chocolate chips',
    ],
    instructions: [
      'Preheat your oven to 350°F (175°C).',
      'In a small bowl, mix the flour and baking soda. Set aside.',
      'In a large bowl, cream together the butter, granulated sugar, and brown sugar until smooth.',
      'Beat in the eggs one at a time, then stir in the vanilla.',
      'Gradually add the dry ingredients to the wet ingredients and mix well.',
      'Fold in the chocolate chips.',
      'Drop rounded tablespoons of cookie dough onto ungreased baking sheets.',
      'Bake for 10-12 minutes or until the edges are lightly golden.',
      'Let the cookies cool on the baking sheets for a few minutes before transferring to wire racks to cool completely.',
    ],
    image:
      'https://img.freepik.com/free-photo/chocolate-chips-cookies-arrangement_23-2149702500.jpg?w=360&t=st=1695617687~exp=1695618287~hmac=11b565f2f8c8eac75a365d93930d46abcfc5587caeb45d5ae658b15dffd5790a',
    type: 'Sweets',
  },

  {
    name: 'Apple Pie',
    ingredients: [
      '6-7 cups peeled, sliced apples',
      '1 cup granulated sugar',
      '2 tablespoons all-purpose flour',
      '1 teaspoon ground cinnamon',
      '1/4 teaspoon salt',
      '1 tablespoon lemon juice',
      '2 pie crusts (homemade or store-bought)',
    ],
    instructions: [
      'Preheat your oven to 425°F (220°C).',
      'In a large bowl, combine the sliced apples, sugar, flour, cinnamon, salt, and lemon juice. Toss to coat.',
      'Place one pie crust in a pie dish and add the apple filling.',
      'Cover with the second pie crust, crimping the edges to seal.',
      'Cut a few slits in the top crust to allow steam to escape.',
      'Bake for 45-55 minutes, or until the crust is golden brown and the filling is bubbling.',
      'Allow the pie to cool before serving.',
    ],
    image:
      'https://img.freepik.com/free-photo/top-view-apple-pie-thanksgiving-with-cutlery-leaves_23-2148638999.jpg?w=740&t=st=1695617809~exp=1695618409~hmac=e9daaa5b1a9d6e66259d87d556cf7aa2897c5e0a6635ac1287defd08e371bd10',
    type: 'Sweets',
  },
  {
    name: 'Chocolate Brownies',
    ingredients: [
      '1 cup butter',
      '2 cups granulated sugar',
      '4 large eggs',
      '1 teaspoon vanilla extract',
      '1 cup all-purpose flour',
      '2/3 cup unsweetened cocoa powder',
      '1/2 teaspoon salt',
      '1/2 teaspoon baking powder',
    ],
    instructions: [
      'Preheat your oven to 350°F (175°C) and grease a 9x13-inch baking pan.',
      'In a microwave-safe bowl, melt the butter. Stir in the sugar until well combined.',
      'Add the eggs one at a time, beating well with each addition. Stir in the vanilla.',
      'In a separate bowl, whisk together the flour, cocoa powder, salt, and baking powder.',
      'Gradually add the dry ingredients to the wet ingredients and mix until just combined.',
      'Pour the batter into the prepared baking pan and spread it evenly.',
      'Bake for 30-35 minutes or until a toothpick inserted into the center comes out with a few moist crumbs.',
      'Allow the brownies to cool in the pan before cutting into squares.',
    ],
    image:
      'https://img.freepik.com/free-photo/indulgent-homemade-chocolate-brownie-fresh-sweet-generated-by-ai_188544-16020.jpg?t=st=1695617840~exp=1695621440~hmac=7b22f551c50b4aa70d41f16f5808779327fe0e387b793bc5de5639a18c5e0002&w=826',
    type: 'Sweets',
  },

  {
    name: 'Banana Bread',
    ingredients: [
      '2-3 ripe bananas, mashed',
      '1/3 cup melted butter',
      '1 cup granulated sugar',
      '1 large egg, beaten',
      '1 teaspoon vanilla extract',
      '1 teaspoon baking soda',
      'Pinch of salt',
      '1 1/2 cups all-purpose flour',
    ],
    instructions: [
      'Preheat your oven to 350°F (175°C). Grease a 4x8-inch loaf pan.',
      'In a mixing bowl, mash the ripe bananas with a fork.',
      'Stir the melted butter into the mashed bananas.',
      'Mix in the sugar, beaten egg, and vanilla extract.',
      'Sprinkle the baking soda and salt over the banana mixture and stir to combine.',
      'Add the flour and stir until just incorporated.',
      'Pour the batter into the greased loaf pan.',
      'Bake for 60-65 minutes, or until a toothpick inserted into the center comes out clean.',
      'Allow the banana bread to cool in the pan for a few minutes before transferring it to a wire rack to cool completely.',
    ],
    image:
      'https://img.freepik.com/free-photo/delicious-banana-bread-table_23-2150764400.jpg?t=st=1695617916~exp=1695621516~hmac=b008dd53bf91c00e6bd40b7125d3d741cd4a233c6dc9c612229774c1491a36c7&w=740',
    type: 'Sweets',
  },
  {
    name: 'Rice Krispie Treats',
    ingredients: [
      '6 cups Rice Krispies cereal',
      '3 tablespoons butter',
      '1 package (10 ounces) marshmallows',
    ],
    instructions: [
      'In a large saucepan, melt the butter over low heat.',
      'Add the marshmallows and stir until completely melted and well combined with the butter.',
      'Remove from heat and quickly stir in the Rice Krispies cereal, mixing until evenly coated.',
      'Press the mixture into a greased 9x13-inch pan using a greased spatula or your hands.',
      'Allow the treats to cool and set before cutting into squares.',
    ],
    image:
      'https://img.freepik.com/free-photo/crunchy-granola-with-fresh-fruit-nuts-generated-by-ai_188544-23099.jpg?t=st=1695617937~exp=1695621537~hmac=be86a773cfc781c6b2018814c53d6b7991c9a88cba3c93dea57d13e68821acbe&w=826',
    type: 'Sweets',
  },
  {
    name: 'Homemade Caramel Popcorn',
    ingredients: [
      '10 cups popped popcorn (about 1/2 cup unpopped kernels)',
      '1 cup unsalted butter',
      '2 cups brown sugar',
      '1/2 cup light corn syrup',
      '1 teaspoon salt',
      '1/2 teaspoon baking soda',
      '1 teaspoon vanilla extract',
    ],
    instructions: [
      'Preheat your oven to 250°F (120°C).',
      'Place the popped popcorn in a large roasting pan.',
      'In a saucepan, melt the butter over medium heat.',
      'Stir in the brown sugar, corn syrup, and salt. Bring to a boil, stirring constantly.',
      'Once boiling, stop stirring and let the mixture cook for 4-5 minutes.',
      'Remove from heat and stir in the baking soda and vanilla extract.',
      'Pour the caramel sauce over the popcorn in the roasting pan and gently stir to coat the popcorn evenly.',
      'Bake in the preheated oven for 45 minutes, stirring every 15 minutes.',
      'Remove from the oven and let the caramel popcorn cool completely before breaking it into pieces.',
    ],
    image:
      'https://img.freepik.com/premium-photo/delicious-caramelcoated-popcorn-delight_841543-19106.jpg?w=826',
    type: 'Sweets',
  },
  {
    name: 'Lemon Bars',
    ingredients: [
      '1 cup all-purpose flour',
      '1/2 cup unsalted butter, softened',
      '1/4 cup powdered sugar',
      '2 large eggs',
      '1 cup granulated sugar',
      '2 tablespoons all-purpose flour',
      '1/2 teaspoon baking powder',
      '1/4 teaspoon salt',
      '2 tablespoons lemon juice',
      '1 tablespoon lemon zest',
      'Powdered sugar for dusting',
    ],
    instructions: [
      'Preheat your oven to 350°F (175°C). Grease a 9x9-inch baking pan.',
      'In a bowl, combine 1 cup of flour, softened butter, and 1/4 cup of powdered sugar. Press this mixture into the bottom of the prepared pan.',
      'Bake for 20 minutes in the preheated oven, or until firm and golden.',
      'In a separate bowl, whisk together the eggs, granulated sugar, 2 tablespoons of flour, baking powder, salt, lemon juice, and lemon zest.',
      'Pour this lemon mixture over the baked crust and return to the oven.',
      'Bake for an additional 20-25 minutes, or until the lemon topping has set and is no longer jiggly.',
      'Let the lemon bars cool in the pan before cutting into squares and dusting with powdered sugar.',
    ],
    image:
      'https://img.freepik.com/free-photo/delicious-ice-cream-arrangement-top-view_23-2150735564.jpg?t=st=1695618022~exp=1695621622~hmac=4f68a9add18f2f7ffc80c9feaf122f482c04555eb9553232789c59b39866435d&w=826',
    type: 'Sweets',
  },
  {
    name: 'Pumpkin Pie',
    ingredients: [
      '1 9-inch unbaked pie crust',
      '1 15-ounce can pumpkin puree',
      '1 cup granulated sugar',
      '1 teaspoon ground cinnamon',
      '1/2 teaspoon ground ginger',
      '1/4 teaspoon ground cloves',
      '1/2 teaspoon salt',
      '2 large eggs',
      '1 12-ounce can evaporated milk',
    ],
    instructions: [
      'Preheat your oven to 425°F (220°C).',
      'In a mixing bowl, combine the pumpkin puree, sugar, cinnamon, ginger, cloves, and salt.',
      'In a separate bowl, beat the eggs and then add them to the pumpkin mixture.',
      'Gradually stir in the evaporated milk.',
      'Pour the filling into the unbaked pie crust.',
      'Bake at 425°F (220°C) for 15 minutes, then reduce the oven temperature to 350°F (175°C) and bake for an additional 40-50 minutes or until a knife inserted into the center comes out clean.',
      'Allow the pumpkin pie to cool before serving.',
    ],
    image:
      'https://img.freepik.com/premium-photo/pumpkin-pie-vintage-baking-dish-created-with-generative-ai_419341-46459.jpg?w=740',
    type: 'Sweets',
  },
  {
    name: 'Chocolate Fondue',
    ingredients: [
      '8 ounces semi-sweet chocolate, chopped',
      '1/2 cup heavy cream',
      '1 teaspoon vanilla extract',
      'Assorted dippers (strawberries, marshmallows, pretzels, bananas, etc.)',
    ],
    instructions: [
      'In a microwave-safe bowl, heat the heavy cream until it begins to simmer.',
      'Add the chopped chocolate and let it sit for a minute to melt.',
      'Stir until the chocolate is completely smooth and combined with the cream.',
      'Stir in the vanilla extract.',
      'Transfer the chocolate fondue to a fondue pot or a heatproof bowl set over a candle or burner to keep it warm.',
      'Serve with assorted dippers for dipping into the chocolate fondue.',
    ],
    image:
      'https://img.freepik.com/free-photo/indulgent-dessert-dark-chocolate-fudge-with-strawberries-generated-by-ai_188544-22763.jpg?t=st=1695618145~exp=1695621745~hmac=1f09e3be74bd122351a5f378cf6ac54a1e2fa456a5258c4b58b2e07742cbc937&w=826',
    type: 'Sweets',
  },
  {
    name: 'Vanilla Cupcakes',
    ingredients: [
      '1 1/2 cups all-purpose flour',
      '1 1/2 teaspoons baking powder',
      '1/4 teaspoon salt',
      '1/2 cup unsalted butter, softened',
      '1 cup granulated sugar',
      '2 large eggs',
      '2 teaspoons vanilla extract',
      '1/2 cup whole milk',
    ],
    instructions: [
      'Preheat your oven to 350°F (175°C) and line a cupcake tin with paper liners.',
      'In a medium bowl, whisk together the flour, baking powder, and salt. Set aside.',
      'In a large bowl, cream together the softened butter and sugar until light and fluffy.',
      'Beat in the eggs one at a time, then stir in the vanilla extract.',
      'Add the dry ingredients to the wet ingredients, alternating with the milk, beginning and ending with the dry mixture. Mix until just combined.',
      'Divide the batter evenly among the cupcake liners, filling each about 2/3 full.',
      'Bake for 18-20 minutes or until a toothpick inserted into the center comes out clean.',
      'Let the cupcakes cool in the tin for a few minutes before transferring to a wire rack to cool completely.',
    ],
    image:
      'https://img.freepik.com/free-photo/view-tray-filled-with-delicious-sweet-cupcake-desserts_23-2150679524.jpg?t=st=1695618179~exp=1695621779~hmac=bd643d442ee8abd7748d51e2f981d470b805e59d9d17e1ed5bd2b32bea0e4607&w=826',
    type: 'Cakes',
  },
  {
    name: 'Strawberry Shortcake',
    ingredients: [
      '1 pound fresh strawberries, hulled and sliced',
      '1/4 cup granulated sugar',
      '2 cups all-purpose flour',
      '1/4 cup granulated sugar',
      '1 tablespoon baking powder',
      '1/2 teaspoon salt',
      '1/2 cup unsalted butter, cold and cubed',
      '1 cup milk',
      '1 cup heavy cream',
      '2 tablespoons powdered sugar',
      '1 teaspoon vanilla extract',
    ],
    instructions: [
      'In a bowl, mix the sliced strawberries with 1/4 cup of sugar. Let them sit for at least 30 minutes to macerate.',
      'Preheat your oven to 425°F (220°C).',
      'In a large bowl, combine the flour, 1/4 cup of sugar, baking powder, and salt.',
      'Cut in the cold, cubed butter until the mixture resembles coarse crumbs.',
      'Add the milk and stir until just combined.',
      'Turn the dough out onto a floured surface and knead it gently a few times.',
      'Pat the dough into a 1-inch thick circle and cut out shortcakes using a round cutter.',
      'Place the shortcakes on a baking sheet and bake for 12-15 minutes or until golden brown.',
      'While the shortcakes cool, whip the heavy cream with powdered sugar and vanilla extract until stiff peaks form.',
      'To serve, split the shortcakes, top with macerated strawberries, and a dollop of whipped cream.',
    ],
    image:
      'https://img.freepik.com/free-photo/close-up-fancy-dessert_23-2150527577.jpg?t=st=1695618211~exp=1695621811~hmac=cf08aba6c5fb5d54ea6e753c67998eb42bcc91147bf497560b8d58878dd944da&w=360',
    type: 'Cakes',
  },

  {
    name: 'Classic Chocolate Cake',
    ingredients: [
      '2 cups all-purpose flour',
      '2 cups granulated sugar',
      '3/4 cup unsweetened cocoa powder',
      '1 1/2 teaspoons baking powder',
      '1 1/2 teaspoons baking soda',
      '1 teaspoon salt',
      '2 large eggs',
      '1 cup buttermilk',
      '1/2 cup vegetable oil',
      '2 teaspoons vanilla extract',
      '1 cup boiling water',
      'For the Chocolate Frosting:',
      '1 cup unsalted butter, softened',
      '1 1/2 cups unsweetened cocoa powder',
      '5 cups powdered sugar',
      '1/2 cup milk',
      '2 teaspoons vanilla extract',
    ],
    instructions: [
      'Preheat your oven to 350°F (175°C). Grease and flour two 9-inch round cake pans.',
      'In a large bowl, sift together the flour, sugar, cocoa powder, baking powder, baking soda, and salt.',
      'Add the eggs, buttermilk, vegetable oil, and vanilla extract. Beat with an electric mixer on medium speed until well combined.',
      "Stir in the boiling water; the batter will be thin but that's okay.",
      'Pour the batter evenly into the prepared pans and bake for 30-35 minutes, or until a toothpick inserted into the center comes out clean.',
      'Allow the cakes to cool in the pans for 10 minutes before transferring to wire racks to cool completely.',
      'For the frosting, beat the softened butter until creamy. Add the cocoa powder, powdered sugar, milk, and vanilla extract. Beat until smooth and creamy.',
      'Once the cakes are completely cool, frost one cake layer, place the second layer on top, and frost the top and sides of the cake.',
    ],
    image:
      'https://img.freepik.com/free-photo/indulgent-chocolate-cheesecake-with-fresh-berry-decoration-generated-by-ai_188544-38490.jpg?t=st=1695618272~exp=1695621872~hmac=bc7e99c1f4fb1999c382889768e1dc50e5985d4b9caf799e21a7003c4f6147b0&w=826',
    type: 'Cakes',
  },
  {
    name: 'Vanilla Sponge Cake',
    ingredients: [
      '2 cups all-purpose flour',
      '2 cups granulated sugar',
      '1 cup unsalted butter, softened',
      '4 large eggs',
      '1 cup milk',
      '1 1/2 teaspoons vanilla extract',
      '2 teaspoons baking powder',
      '1/2 teaspoon salt',
    ],
    instructions: [
      'Preheat your oven to 350°F (175°C). Grease and flour two 9-inch round cake pans.',
      'In a mixing bowl, cream the butter and sugar until light and fluffy.',
      'Add the eggs one at a time, beating well after each addition. Stir in the vanilla extract.',
      'In a separate bowl, whisk together the flour, baking powder, and salt.',
      'Gradually add the dry ingredients to the wet ingredients, alternating with the milk, beginning and ending with the dry mixture. Mix until just combined.',
      'Divide the batter evenly between the prepared pans and bake for 25-30 minutes or until a toothpick inserted into the center comes out clean.',
      'Allow the cakes to cool in the pans for 10 minutes before transferring to wire racks to cool completely.',
      'Once the cakes are cool, you can frost or decorate them as desired.',
    ],
    image:
      'https://img.freepik.com/free-photo/delicious-cake-with-fruits_23-2150727594.jpg?t=st=1695618319~exp=1695621919~hmac=6a1e38d9a64563f77af64f857d1fb444d61a59202e8bf716024e539d849ee6b8&w=740',
    type: 'Cakes',
  },
  {
    name: 'Carrot Cake',
    ingredients: [
      '2 cups all-purpose flour',
      '2 cups granulated sugar',
      '1 1/2 teaspoons baking powder',
      '1 teaspoon baking soda',
      '1/2 teaspoon salt',
      '1 teaspoon ground cinnamon',
      '1/2 teaspoon ground nutmeg',
      '1/2 cup vegetable oil',
      '4 large eggs',
      '1 teaspoon vanilla extract',
      '2 cups grated carrots',
      '1/2 cup crushed pineapple, drained',
      '1/2 cup chopped walnuts',
      'For the Cream Cheese Frosting:',
      '8 ounces cream cheese, softened',
      '1/2 cup unsalted butter, softened',
      '4 cups powdered sugar',
      '1 teaspoon vanilla extract',
    ],
    instructions: [
      'Preheat your oven to 350°F (175°C). Grease and flour a 9x13-inch baking pan or two 9-inch round cake pans.',
      'In a large bowl, sift together the flour, sugar, baking powder, baking soda, salt, cinnamon, and nutmeg.',
      'In another bowl, whisk together the vegetable oil, eggs, and vanilla extract.',
      'Add the wet ingredients to the dry ingredients and mix until well combined.',
      'Fold in the grated carrots, crushed pineapple, and chopped walnuts.',
      'Pour the batter into the prepared pan(s) and bake for 30-35 minutes (or 25-30 minutes for round pans) until a toothpick inserted into the center comes out clean.',
      'Allow the cake(s) to cool completely.',
      'For the cream cheese frosting, beat together the softened cream cheese and butter until creamy and smooth.',
      'Gradually add the powdered sugar and vanilla extract, beating until the frosting is fluffy and well combined.',
      'Frost the cooled cake(s) with the cream cheese frosting.',
    ],
    image:
      'https://img.freepik.com/free-photo/delicious-carrot-cake-with-cream_23-2150727528.jpg?t=st=1695618528~exp=1695622128~hmac=e5f03dc386bba1f3e75c94d00ba39fdcc8c36730bb9d3d227e5ebf25a0235be5&w=740',
    type: 'Cakes',
  },
  {
    name: 'Lemon Pound Cake',
    ingredients: [
      '1 1/2 cups all-purpose flour',
      '1 1/2 cups granulated sugar',
      '1 cup unsalted butter, softened',
      '4 large eggs',
      '1/4 cup lemon juice',
      '2 tablespoons lemon zest',
      '1/2 teaspoon vanilla extract',
      '1/2 cup sour cream',
      '1/2 teaspoon baking powder',
      '1/2 teaspoon baking soda',
      '1/2 teaspoon salt',
      'For the Lemon Glaze:',
      '1 cup powdered sugar',
      '2-3 tablespoons lemon juice',
    ],
    instructions: [
      'Preheat your oven to 325°F (160°C). Grease and flour a 9x5-inch loaf pan or a bundt cake pan.',
      'In a mixing bowl, cream together the softened butter and sugar until light and fluffy.',
      'Add the eggs one at a time, beating well after each addition. Stir in the lemon juice, lemon zest, and vanilla extract.',
      'In a separate bowl, whisk together the flour, baking powder, baking soda, and salt.',
      'Add the dry ingredients to the wet ingredients, alternating with the sour cream, beginning and ending with the dry mixture. Mix until just combined.',
      'Pour the batter into the prepared pan and bake for 60-70 minutes, or until a toothpick inserted into the center comes out clean.',
      'Allow the cake to cool in the pan for 10 minutes before transferring to a wire rack to cool completely.',
      'For the lemon glaze, whisk together the powdered sugar and lemon juice until smooth. Drizzle the glaze over the cooled cake.',
    ],
    image:
      'https://img.freepik.com/free-photo/ai-generated-cake-picture_23-2150649369.jpg?t=st=1695618562~exp=1695622162~hmac=91d7f68d6dfecafdafb0cdfc6168f508a1850ee6d606f8f0d468b6bd68f2ad63&w=826',
    type: 'Cakes',
  },
  {
    name: 'Red Velvet Cake',
    ingredients: [
      '2 1/2 cups all-purpose flour',
      '1 1/2 cups granulated sugar',
      '1 teaspoon baking powder',
      '1 teaspoon baking soda',
      '1 teaspoon salt',
      '2 tablespoons unsweetened cocoa powder',
      '1 1/2 cups vegetable oil',
      '1 cup buttermilk',
      '2 large eggs',
      '2 tablespoons red food coloring',
      '1 teaspoon vanilla extract',
      '1 teaspoon white vinegar',
      'For the Cream Cheese Frosting:',
      '8 ounces cream cheese, softened',
      '1/2 cup unsalted butter, softened',
      '4 cups powdered sugar',
      '1 teaspoon vanilla extract',
    ],
    instructions: [
      'Preheat your oven to 350°F (175°C). Grease and flour two 9-inch round cake pans.',
      'In a large bowl, sift together the flour, sugar, baking powder, baking soda, salt, and cocoa powder.',
      'In another bowl, whisk together the vegetable oil, buttermilk, eggs, food coloring, vanilla extract, and white vinegar.',
      'Add the wet ingredients to the dry ingredients and mix until well combined.',
      'Divide the batter evenly between the prepared pans and bake for 25-30 minutes, or until a toothpick inserted into the center comes out clean.',
      'Allow the cakes to cool in the pans for 10 minutes before transferring to wire racks to cool completely.',
      'For the cream cheese frosting, beat together the softened cream cheese and butter until creamy and smooth.',
      'Gradually add the powdered sugar and vanilla extract, beating until the frosting is fluffy and well combined.',
      'Frost the cooled cake with the cream cheese frosting.',
    ],
    image:
      'https://img.freepik.com/free-photo/delicious-cake-with-fruits_23-2150727705.jpg?t=st=1695618603~exp=1695622203~hmac=6ca8b0ea6444afc12b8b7e0a05aec390c52f835000a99da2cda0e7291cbd8cd9&w=740',
    type: 'Cakes',
  },

  {
    name: 'Tiramisu',
    ingredients: [
      '6 egg yolks',
      '3/4 cup granulated sugar',
      '1 cup mascarpone cheese',
      '1 1/2 cups strong brewed coffee, cooled',
      '3 tablespoons coffee liqueur (optional)',
      '1 package ladyfingers',
      'Cocoa powder, for dusting',
      'Unsweetened cocoa powder, for garnish',
    ],
    instructions: [
      'In a heatproof bowl, whisk together the egg yolks and sugar until well combined.',
      'Place the bowl over a pot of simmering water (double boiler) and whisk continuously until the mixture thickens, about 8-10 minutes. Remove from heat and let it cool.',
      'Fold the mascarpone cheese into the egg yolk mixture until smooth.',
      'In a shallow dish, combine the brewed coffee and coffee liqueur, if using.',
      'Quickly dip each ladyfinger into the coffee mixture and layer them in the bottom of a serving dish or individual glasses.',
      'Spread half of the mascarpone mixture over the ladyfingers.',
      'Repeat with another layer of dipped ladyfingers and the remaining mascarpone mixture.',
      'Cover and refrigerate for at least 2 hours or overnight.',
      'Before serving, dust the top with cocoa powder and garnish with unsweetened cocoa powder.',
    ],
    image:
      'https://img.freepik.com/free-photo/plate-tiramisu-with-cup-coffee-background_188544-17893.jpg?t=st=1695618859~exp=1695622459~hmac=a579e2e0ca7404d5d8917fd87527e8813f89e4f2169afb3998d86d9e2a4f3581&w=826',
    type: 'Dessert',
  },
  {
    name: 'Panna Cotta',
    ingredients: [
      '2 cups heavy cream',
      '1/2 cup whole milk',
      '1/2 cup granulated sugar',
      '1 vanilla bean, split lengthwise (or 1 teaspoon vanilla extract)',
      '2 1/4 teaspoons gelatin powder',
      '3 tablespoons cold water',
      'Fresh berries, for garnish',
      'Mint leaves, for garnish',
    ],
    instructions: [
      'In a saucepan, combine the heavy cream, whole milk, and sugar.',
      'Scrape the seeds from the vanilla bean and add both the seeds and the pod to the saucepan. Alternatively, use vanilla extract.',
      "Heat the mixture over medium heat, stirring until it's hot but not boiling. Remove the vanilla pod.",
      'In a small bowl, sprinkle the gelatin over the cold water and let it sit for a few minutes to bloom.',
      'Add the bloomed gelatin to the cream mixture and stir until completely dissolved.',
      'Pour the mixture into ramekins or serving glasses. Refrigerate for at least 4 hours or until set.',
      'Before serving, garnish with fresh berries and mint leaves.',
    ],
    image:
      'https://img.freepik.com/free-photo/delicious-banana-dessert_23-2150764410.jpg?t=st=1695618891~exp=1695622491~hmac=606c6fd78d6187f8360b52eda07e09ef44b3d0113eac70a61c458e98357d115b&w=740',
    type: 'Dessert',
  },
  {
    name: 'Chocolate Fondue',
    ingredients: [
      '8 ounces semi-sweet chocolate, chopped',
      '1/2 cup heavy cream',
      '1 teaspoon vanilla extract',
      'Assorted dippers (strawberries, marshmallows, pretzels, bananas, etc.)',
    ],
    instructions: [
      'In a microwave-safe bowl, heat the heavy cream until it begins to simmer.',
      'Add the chopped chocolate and let it sit for a minute to melt.',
      'Stir until the chocolate is completely smooth and combined with the cream.',
      'Stir in the vanilla extract.',
      'Transfer the chocolate fondue to a fondue pot or a heatproof bowl set over a candle or burner to keep it warm.',
      'Serve with assorted dippers for dipping into the chocolate fondue.',
    ],
    image:
      'https://img.freepik.com/premium-photo/chocolate-fondue-with-fruits-toast_949611-486.jpg?w=740',
    type: 'Dessert',
  },
  {
    name: 'Strawberry Shortcake',
    ingredients: [
      '1 pound fresh strawberries, hulled and sliced',
      '1/4 cup granulated sugar',
      '2 cups all-purpose flour',
      '1/4 cup granulated sugar',
      '1 tablespoon baking powder',
      '1/2 teaspoon salt',
      '1/2 cup unsalted butter, cold and cubed',
      '1 cup milk',
      '1 cup heavy cream',
      '2 tablespoons powdered sugar',
      '1 teaspoon vanilla extract',
    ],
    instructions: [
      'In a bowl, mix the sliced strawberries with 1/4 cup of sugar. Let them sit for at least 30 minutes to macerate.',
      'Preheat your oven to 425°F (220°C).',
      'In a large bowl, combine the flour, 1/4 cup of sugar, baking powder, and salt.',
      'Cut in the cold, cubed butter until the mixture resembles coarse crumbs.',
      'Add the milk and stir until just combined.',
      'Turn the dough out onto a floured surface and knead it gently a few times.',
      'Pat the dough into a 1-inch thick circle and cut out shortcakes using a round cutter.',
      'Place the shortcakes on a baking sheet and bake for 12-15 minutes or until golden brown.',
      'While the shortcakes cool, whip the heavy cream with powdered sugar and vanilla extract until stiff peaks form.',
      'To serve, split the shortcakes, top with macerated strawberries, and a dollop of whipped cream.',
    ],
    image:
      'https://img.freepik.com/free-photo/close-up-fancy-dessert_23-2150527566.jpg?t=st=1695619009~exp=1695622609~hmac=49bbfe55b7c8754622532817486f810b1cf926cdfadf6fef7933aff78fffc605&w=360',
    type: 'Dessert',
  },
  {
    name: 'Banana Split',
    ingredients: [
      '3 ripe bananas, split lengthwise',
      '3 scoops each of chocolate, vanilla, and strawberry ice cream',
      '1/4 cup chocolate sauce',
      '1/4 cup strawberry sauce',
      '1/4 cup crushed pineapple, drained',
      '1/4 cup chopped nuts (e.g., walnuts or peanuts)',
      'Whipped cream',
      'Maraschino cherries',
    ],
    instructions: [
      'Place the banana halves in a long dish or on individual serving plates.',
      'Add scoops of chocolate, vanilla, and strawberry ice cream between the banana halves.',
      'Drizzle chocolate sauce, strawberry sauce, and crushed pineapple over the ice cream.',
      'Sprinkle with chopped nuts.',
      'Top with whipped cream and maraschino cherries.',
      'Serve immediately and enjoy your banana split!',
    ],
    image:
      'https://img.freepik.com/premium-photo/hyper-detailed-close-up-shot-classic-banana-split-dessert-featuring-split-banana_933496-20079.jpg?w=826',
    type: 'Dessert',
  },

  {
    name: 'Vanilla Ice Cream',
    type: 'Ice Creams',
    ingredients: [
      '2 cups heavy cream',
      '1 cup whole milk',
      '3/4 cup granulated sugar',
      '2 tablespoons pure vanilla extract',
      'Pinch of salt',
    ],
    instructions: [
      'In a mixing bowl, whisk together the heavy cream, whole milk, sugar, vanilla extract, and a pinch of salt until the sugar is completely dissolved.',
      "Pour the mixture into an ice cream maker and churn according to the manufacturer's instructions.",
      'Once churned, transfer the ice cream to an airtight container and freeze for a few hours or until firm.',
      'Scoop and serve as desired.',
    ],
    image:
      'https://img.freepik.com/free-photo/delicious-ice-cream-with-topping_23-2150735434.jpg?t=st=1695619163~exp=1695622763~hmac=aafa79ec2caf7cb9b66ddf6610fd2d60d5799683c3429218b76c6ecb7d973f8d&w=740',
  },
  {
    name: 'Chocolate Ice Cream',
    type: 'Ice Creams',
    ingredients: [
      '2 cups heavy cream',
      '1 cup whole milk',
      '3/4 cup granulated sugar',
      '3/4 cup unsweetened cocoa powder',
      '2 teaspoons pure vanilla extract',
      'Pinch of salt',
    ],
    instructions: [
      'In a mixing bowl, whisk together the heavy cream, whole milk, sugar, cocoa powder, vanilla extract, and a pinch of salt until the sugar and cocoa powder are completely dissolved.',
      "Pour the mixture into an ice cream maker and churn according to the manufacturer's instructions.",
      'Once churned, transfer the ice cream to an airtight container and freeze for a few hours or until firm.',
      'Scoop and serve as desired.',
    ],
    image:
      'https://img.freepik.com/free-photo/delicious-chocolate-ice-cream-bowl_23-2150735562.jpg?t=st=1695619247~exp=1695622847~hmac=d54ab41fa871f386616aded24045d55d60328e2284072c2671e6db580df96154&w=996',
  },
  {
    name: 'Strawberry Ice Cream',
    type: 'Ice Creams',
    ingredients: [
      '2 cups fresh strawberries, hulled and sliced',
      '1 cup heavy cream',
      '1 cup whole milk',
      '3/4 cup granulated sugar',
      '2 teaspoons pure vanilla extract',
    ],
    instructions: [
      'In a blender, puree the fresh strawberries until smooth.',
      'In a mixing bowl, combine the strawberry puree, heavy cream, whole milk, sugar, and vanilla extract. Mix until well combined.',
      "Pour the mixture into an ice cream maker and churn according to the manufacturer's instructions.",
      'Once churned, transfer the strawberry ice cream to an airtight container and freeze for a few hours or until firm.',
      'Scoop and serve as desired.',
    ],
    image:
      'https://img.freepik.com/free-photo/delicious-ice-cream-studio_23-2150696686.jpg?t=st=1695619289~exp=1695622889~hmac=7713ff9be6f7cb26f9e8808bcacd46fb40e6f71c8a50eb5fdeba4326ddbdb229&w=360',
  },
  {
    name: 'Mint Chocolate Chip Ice Cream',
    type: 'Ice Creams',
    ingredients: [
      '2 cups heavy cream',
      '1 cup whole milk',
      '3/4 cup granulated sugar',
      '1 teaspoon pure peppermint extract',
      'Green food coloring (optional)',
      '1 cup semi-sweet chocolate chips',
    ],
    instructions: [
      'In a mixing bowl, whisk together the heavy cream, whole milk, sugar, peppermint extract, and a few drops of green food coloring (if desired) until the sugar is completely dissolved.',
      "Pour the mixture into an ice cream maker and churn according to the manufacturer's instructions.",
      'During the last few minutes of churning, add the semi-sweet chocolate chips to the ice cream.',
      'Once churned and mixed, transfer the mint chocolate chip ice cream to an airtight container and freeze for a few hours or until firm.',
      'Scoop and serve as desired.',
    ],
    image:
      'https://img.freepik.com/free-photo/delicious-ice-cream-studio_23-2150696829.jpg?t=st=1695619315~exp=1695622915~hmac=24a0e5a3970db44bb6cecf0f2271b9f5a1475820652888822c3e60655ac9211c&w=360',
  },
  {
    name: 'Cookies and Cream Ice Cream',
    type: 'Ice Creams',
    ingredients: [
      '2 cups heavy cream',
      '1 cup whole milk',
      '3/4 cup granulated sugar',
      '2 teaspoons pure vanilla extract',
      '20 chocolate sandwich cookies, crushed into pieces',
    ],
    instructions: [
      'In a mixing bowl, whisk together the heavy cream, whole milk, sugar, and vanilla extract until the sugar is completely dissolved.',
      "Pour the mixture into an ice cream maker and churn according to the manufacturer's instructions.",
      'During the last few minutes of churning, add the crushed chocolate sandwich cookies to the ice cream.',
      'Once churned and mixed, transfer the cookies and cream ice cream to an airtight container and freeze for a few hours or until firm.',
      'Scoop and serve as desired.',
    ],
    image:
      'https://img.freepik.com/premium-photo/bowl-chocolate-chip-cookie-dough-ice-cream-with-chunks-cookie-dough-visible_951187-605.jpg?w=740',
  },

  {
    name: 'Orange Juice',
    type: 'Juices',
    ingredients: ['4-6 large oranges'],
    instructions: [
      'Wash and peel the oranges, removing any seeds if present.',
      'Cut the oranges into smaller pieces that will fit into your juicer.',
      'Feed the orange pieces through the juicer to extract the juice.',
      'Pour the fresh orange juice into a glass and serve immediately.',
    ],
    image:
      'https://img.freepik.com/free-photo/fresh-citrus-slice-rustic-wood-table-generative-ai_188544-8669.jpg?t=st=1695619481~exp=1695623081~hmac=7e2d08ab2d2a15443420ec9a882997a3a394e450b7da75e7392087e3767a07ea&w=826',
  },
  {
    name: 'Apple Juice',
    type: 'Juices',
    ingredients: ['4-6 apples (any variety)'],
    instructions: [
      'Wash and core the apples, leaving the skin on for added flavor and nutrients.',
      'Cut the apples into smaller pieces that will fit into your juicer.',
      'Feed the apple pieces through the juicer to extract the juice.',
      'Pour the fresh apple juice into a glass and serve immediately.',
    ],
    image:
      'https://img.freepik.com/premium-photo/glass-apple-juice-fruits_614506-359.jpg?w=740',
  },
  {
    name: 'Carrot Juice',
    type: 'Juices',
    ingredients: ['4-6 large carrots'],
    instructions: [
      'Wash and peel the carrots, trimming off the ends.',
      'Cut the carrots into smaller pieces that will fit into your juicer.',
      'Feed the carrot pieces through the juicer to extract the juice.',
      'Pour the fresh carrot juice into a glass and serve immediately.',
    ],
    image:
      'https://img.freepik.com/premium-photo/photo-yummy-healthy-pure-carrot-juice-glass_763111-35916.jpg?w=740',
  },
  {
    name: 'Strawberry Banana Smoothie',
    type: 'Juices',
    ingredients: [
      '1 cup fresh strawberries, hulled',
      '1 ripe banana',
      '1/2 cup Greek yogurt',
      '1/2 cup orange juice',
      '1 tablespoon honey (optional)',
    ],
    instructions: [
      'Place the strawberries, banana, Greek yogurt, orange juice, and honey (if using) in a blender.',
      'Blend until smooth and creamy.',
      'Pour the strawberry banana smoothie into a glass and serve immediately.',
    ],
    image:
      'https://img.freepik.com/premium-photo/highcalorie-milkshake-with-fresh-fruits-dark-background-tall-glass-with-straw_990017-2184.jpg?w=740',
  },
  {
    name: 'Green Juice',
    type: 'Juices',
    ingredients: [
      '2 cups kale leaves, stems removed',
      '1 cucumber',
      '2 green apples',
      '1 lemon, peeled',
      '1-inch piece of fresh ginger',
    ],
    instructions: [
      'Wash all the ingredients thoroughly.',
      'Cut the cucumber, green apples, and lemon into smaller pieces that will fit into your juicer.',
      'Feed the kale, cucumber, green apples, lemon, and ginger through the juicer to extract the juice.',
      'Pour the fresh green juice into a glass and serve immediately.',
    ],
    image:
      'https://img.freepik.com/free-photo/organic-vegetable-smoothie-healthy-gourmet-drink-summer-refreshment-generated-by-ai_188544-56188.jpg?t=st=1695619673~exp=1695623273~hmac=d060a7c117669b0ba8d7ddc5373870d9af4820ce1b19584afee3f09f1fca2cf5&w=826',
  },

  {
    name: 'Tomato Soup',
    type: 'Soups',
    ingredients: [
      '4 cups tomatoes, chopped',
      '1 onion, chopped',
      '2 cloves garlic, minced',
      '2 cups vegetable broth',
      '1/2 cup heavy cream',
      '2 tablespoons olive oil',
      '1 teaspoon dried basil',
      'Salt and pepper to taste',
      'Fresh basil leaves for garnish (optional)',
    ],
    instructions: [
      'In a large pot, heat the olive oil over medium heat. Add the chopped onions and cook until they become translucent.',
      'Add the minced garlic and cook for another minute.',
      'Add the chopped tomatoes and dried basil. Cook for 5-7 minutes, stirring occasionally, until the tomatoes soften.',
      'Pour in the vegetable broth and bring the mixture to a boil. Reduce heat, cover, and simmer for 15-20 minutes.',
      'Use an immersion blender to puree the soup until smooth. Alternatively, transfer the mixture to a blender in batches and blend until smooth, then return to the pot.',
      'Stir in the heavy cream and heat the soup gently. Season with salt and pepper to taste.',
      'Serve hot, garnished with fresh basil leaves if desired.',
    ],
    image:
      'https://img.freepik.com/premium-photo/photo-bowl-tomato-soup-with-roll-side_924629-7762.jpg?w=740',
  },
  {
    name: 'Chicken Noodle Soup',
    type: 'Soups',
    ingredients: [
      '2 boneless, skinless chicken breasts',
      '8 cups chicken broth',
      '1 cup carrots, sliced',
      '1 cup celery, chopped',
      '1 cup onion, chopped',
      '2 cloves garlic, minced',
      '2 cups egg noodles',
      '2 tablespoons olive oil',
      '1 teaspoon dried thyme',
      'Salt and pepper to taste',
      'Fresh parsley for garnish (optional)',
    ],
    instructions: [
      'In a large pot, heat the olive oil over medium heat. Add the chopped onions, carrots, and celery. Cook for 5-7 minutes until the vegetables soften.',
      'Add the minced garlic and dried thyme. Cook for another minute.',
      'Add the chicken breasts and chicken broth to the pot. Bring to a boil, then reduce heat, cover, and simmer for 20-25 minutes or until the chicken is cooked through.',
      'Remove the chicken breasts from the pot and shred them using two forks. Return the shredded chicken to the pot.',
      'Add the egg noodles and cook until they are tender, about 8-10 minutes.',
      'Season the soup with salt and pepper to taste.',
      'Serve hot, garnished with fresh parsley if desired.',
    ],
    image:
      'https://img.freepik.com/free-photo/freshly-cooked-gourmet-meal-ready-eat-generated-by-ai_24640-81613.jpg?t=st=1695619814~exp=1695623414~hmac=c0a6774f396da25041f1ae3aa55ac7dc158cad692b570820d5ab82859a3744fe&w=826',
  },
  {
    name: 'Minestrone Soup',
    type: 'Soups',
    ingredients: [
      '1 cup pasta (e.g., small shells or macaroni)',
      '2 cups vegetable broth',
      '2 cups water',
      '1 can (15 ounces) diced tomatoes',
      '1 cup carrots, diced',
      '1 cup celery, diced',
      '1 cup zucchini, diced',
      '1 cup canned kidney beans, drained and rinsed',
      '1 cup canned cannellini beans, drained and rinsed',
      '1 cup green beans, cut into 1-inch pieces',
      '1 cup fresh spinach, chopped',
      '1 onion, chopped',
      '2 cloves garlic, minced',
      '1 teaspoon dried basil',
      '1 teaspoon dried oregano',
      'Salt and pepper to taste',
      'Grated Parmesan cheese for garnish (optional)',
    ],
    instructions: [
      'In a large pot, heat some olive oil over medium heat. Add the chopped onions, carrots, and celery. Cook for 5-7 minutes until the vegetables soften.',
      'Add the minced garlic, dried basil, dried oregano, salt, and pepper. Cook for another minute.',
      'Add the diced tomatoes, vegetable broth, water, and pasta to the pot. Bring to a boil, then reduce heat and simmer for about 10 minutes.',
      'Stir in the zucchini, green beans, kidney beans, cannellini beans, and spinach. Cook for another 10 minutes or until the vegetables are tender.',
      'Season the soup with salt and pepper to taste.',
      'Serve hot, garnished with grated Parmesan cheese if desired.',
    ],
    image:
      'https://img.freepik.com/free-photo/homemade-vegetable-soup-fresh-healthy-meal-generated-by-ai_188544-15290.jpg?t=st=1695619911~exp=1695623511~hmac=71460ee112711363490ce5c166dd1732ec0cac09799df7bbda2325bcfd8ea695&w=826',
  },
  {
    name: 'Broccoli Cheddar Soup',
    type: 'Soups',
    ingredients: [
      '4 cups broccoli florets',
      '2 cups sharp cheddar cheese, shredded',
      '4 cups vegetable broth',
      '1 cup whole milk',
      '1/2 cup heavy cream',
      '1 onion, chopped',
      '2 cloves garlic, minced',
      '2 tablespoons butter',
      '2 tablespoons all-purpose flour',
      'Salt and pepper to taste',
    ],
    instructions: [
      'In a large pot, melt the butter over medium heat. Add the chopped onions and cook until they become translucent.',
      'Add the minced garlic and cook for another minute.',
      'Stir in the all-purpose flour and cook for 2-3 minutes until it forms a roux.',
      'Gradually whisk in the vegetable broth, whole milk, and heavy cream. Bring to a simmer and cook for about 10 minutes, stirring occasionally.',
      'Add the broccoli florets to the pot and cook for an additional 10-15 minutes or until the broccoli is tender.',
      'Use an immersion blender to puree the soup until smooth. Alternatively, transfer the mixture to a blender in batches and blend until smooth, then return to the pot.',
      'Stir in the shredded cheddar cheese until it melts and the soup is creamy.',
      'Season with salt and pepper to taste.',
      'Serve hot.',
    ],
    image:
      'https://img.freepik.com/free-photo/view-delicious-cream-soup_23-2150777755.jpg?t=st=1695619936~exp=1695623536~hmac=0bdb060aa0ebbfd138173f1621da6008c621964afe6bf829d2ea459bb3f0f4d2&w=360',
  },
  {
    name: 'Lentil Soup',
    type: 'Soups',
    ingredients: [
      '1 cup dried green or brown lentils, rinsed and drained',
      '8 cups vegetable broth',
      '1 onion, chopped',
      '2 carrots, chopped',
      '2 celery stalks, chopped',
      '2 cloves garlic, minced',
      '1 teaspoon ground cumin',
      '1/2 teaspoon ground turmeric',
      '1/2 teaspoon paprika',
      '1 bay leaf',
      'Salt and pepper to taste',
      'Juice of 1 lemon',
      'Fresh cilantro leaves for garnish (optional)',
    ],
    instructions: [
      'In a large pot, heat some olive oil over medium heat. Add the chopped onions, carrots, and celery. Cook for 5-7 minutes until the vegetables soften.',
      'Add the minced garlic, ground cumin, ground turmeric, paprika, salt, and pepper. Cook for another minute.',
      'Stir in the lentils and vegetable broth. Add the bay leaf.',
      'Bring the mixture to a boil, then reduce heat, cover, and simmer for about 25-30 minutes or until the lentils are tender.',
      'Remove the bay leaf and discard it.',
      'Stir in the lemon juice.',
      'Serve hot, garnished with fresh cilantro leaves if desired.',
    ],
    image:
      'https://img.freepik.com/free-photo/fresh-gourmet-meal-rustic-wooden-table-generated-by-ai_188544-37374.jpg?t=st=1695619962~exp=1695623562~hmac=ebddb8ae3cf47c72fbb4f28ac57236942da420f7f571dd846ed648f7c996ca43&w=826',
  },
];
